name: Run

on:
  schedule:
  - cron:  '*/5 * * * *'

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: yarn --production --frozen-lockfile

    - name: Start script
      env:
        ACKEE_ENDPOINT: ${{ secrets.ACKEE_EDNPOINT }}
        ACKEE_TOKEN: ${{ secrets.ACKEE_TOKEN }}
      run: yarn start
